select
  scan_result_uu_id as scan_result_uuid
  , member_uu_id as member_uuid
  , member_id
  , email
  , height
  , gender
  , age
  , test_datetime
  , weight
  , tbw
  , icw
  , ecw
  , dlm
  , bfm
  , lbm
  , smm
  , bmi
  , pbf
  , lbm_of_right_arm
  , lbm_percent_of_right_arm
  , lbm_of_left_arm
  , lbm_percent_of_left_arm
  , lbm_of_trunk
  , lbm_percent_of_trunk
  , lbm_of_right_leg
  , lbm_percent_of_right_leg
  , lbm_of_left_leg
  , lbm_percent_of_left_leg
  , tbw_of_right_arm
  , tbw_of_left_arm
  , tbw_of_trunk
  , tbw_of_right_leg
  , tbw_of_left_leg
  , icw_of_right_arm
  , icw_of_left_arm
  , icw_of_trunk
  , icw_of_right_leg
  , icw_of_left_leg
  , ecw_of_right_arm
  , ecw_of_left_arm
  , ecw_of_trunk
  , ecw_of_right_leg
  , ecw_of_left_leg
  , ecw_over_tbw
  , ecw_over_tbw_of_right_arm
  , ecw_over_tbw_of_left_arm
  , ecw_over_tbw_of_trunk
  , ecw_over_tbw_of_right_leg
  , ecw_over_tbw_of_left_leg
  , bfm_of_right_arm
  , bfm_percent_of_right_arm
  , bfm_of_left_arm
  , bfm_percent_of_left_arm
  , bfm_of_trunk
  , bfm_percent_of_trunk
  , bfm_of_right_leg
  , bfm_percent_of_right_leg
  , bfm_of_left_leg
  , bfm_percent_of_left_leg
  , bfm_control
  , lbm_control
  , bmr
  , vfl
  , vfa
  , bcm
  , tbw_over_lbm
  , in_body_type
  , wt_graph_scale
  , smm_graph_scale
  , bfm_graph_scale
  , pwt
  , psmm
  , pfatnew
  , bfm__v_double
  , lbm_percent_of_right_arm__v_double
  , lbm_percent_of_trunk__v_double
  , lbm_percent_of_right_leg__v_double
  , lbm_of_left_leg__v_double
  , _dlt_load_id
  , _dlt_id
from
  {{ source('orange_theory_delta', 'body_composition') }}
