[runtime]
dlthub_telemetry = true
log_level="INFO"

[load]
workers=3
delete_completed_jobs=true

[destination.filesystem]
bucket_url = '.'
table_format = "deltalake"

[destination.relative_destination]

[normalize]
loader_file_format="parquet"

[normalize.data_writer]
disable_compression=false
