[runtime]
dlthub_telemetry = true
log_level="INFO"

[load]
workers=3

[destination.filesystem]
bucket_url = '.'
table_format = "deltalake"

[destination.relative_destination]

[normalize]
loader_file_format="jsonl"

[normalize.data_writer]
disable_compression=false
